### ISSUE TITLE
Questions about headings

### ISSUE THREAD

**Issue by rbeezer** [BooksHTML/mathbook-assets#39]
Ok, this is just a consolidated question/comment, since I'm unsure where all this lives.  I don't need long answers, just mostly some yes/no/upcoming guidance.

I am consolidating the production of .type, .codenumber, .title spans into one template (maybe two eventually, depending on answers).

1.  How do I control if the type is shown?  I want "Chapter" and "Theorem", but not "Subsection" (David: I am just mimicing latex output for now, we can standardize later if necessary.)  Do I use a class somewhere?  Maybe this is in-progress/outstanding.

2.  Is MBX responsible for printing spaces between these three spans?  Confused about this one.  Perhaps also in progress?

3.  "Proof."  versus "Proof of Lagrange's Theorem."  Should "Proof" come from the .type and the title is "of Lagrange's Theorem", so it is just appended?  Or should the title be the latter string, and the .type is supressed (via 1 above)?  Does my localization of "Proof" play into this?

4.  MBX space before the period is *not* due to my whitespace control, I think.  The  xsltproc  is obeying the "output='html'" directive and is issuing its own linebreaks.  For example the toc items have sensible linebreaks.  The h5 seems not to, and gets an extra line-break after the last span, prior to ending h5.  Or something.  I'll keep after it.

5.  I have one author who prefers:  2.6.3 Theorem.  Is this easy with CSS?  Do not spend time on this, it should not derail other work.  (David: I think this is reasonable to support - there is a latex package which does it, so you might pick up the choice easily.  Have you seen this much?  Or is it totally oddball?)

6.  If the h5 .heading, or the three spans become the clickable content of a knowl, will the knowl's CSS win or the mathbook CSS?  I think I had trouble with that a few weeks ago.  An example of how to markup

Theorem 6.2 Lagrange's Theorem

inside of a knowl anchor tag might be helpful for me in the next few days.

Thanks,
Rob

**Comment by davidfarmer** [comment]
Closing because this seems to be working now.
