### ISSUE TITLE
Knowled sub-environments

### ISSUE THREAD

**Issue by rbeezer** [BooksHTML/mathbook-assets#42]
A serious question about knowls within environments (an "environment" being a small enough piece of information you would reasonably knowlize it).

In FCLA, we displayed statements of theorems with a "Proof" knowl just below.  (Minor, but relevant, digression: I think it would be nice to place this knowl-link inline with the last words of the statement, appropriately set-off a bit.)

I can think of two other entirely similar cases: 

a "note" (annotation) of a bibliography item.

"hint", "answer", "solution" of an exercise.

The latter should *always* be born hidden in a knowl, and I think notes (annotations) and proofs are an excellent use of knowls.

In current HTML, when we show a theorem and proof on a page (no knowling) they are in two <article>s at the same level.

It feels much more natural to me, and I know David and I have gone back and forth on this one, to have the proof-article nested inside of the theorem-article.  This should not preclude a proof-article from existing independent of a theorem, as authors will certainly do.  And they would have to stand on their own, so that as content of displayed knowl they get styled right independent of their statement.

If this was the case, it would be much easier to slide a "Proof" knowl-link closer to the statement (and not outisde the proof-article.

Right now, just because it is part of my current generalizations, I write the proof-article inside the theorem-article.  The theorem-CSS then italicizes the proof-text.

David: Could you live with putting an adjacent proof inside an element enclosing the statement?  It should not impact the ability to have proofs far away from their statements.

Michael: would it be conceivable this late in the project to have CSS so that .proof, .note, .hint, .answer, .solution  exist as children of the obvious parent and also be standalone elements?  Don't make any changes until David and I have the discussion, but any technical barriers would be good to hear about now.

Rob

**Comment by davidfarmer** [comment]
Closing, because things seem okay in the html.  May need to think more about the MBX.
