### ISSUE TITLE
CSS list types

### ISSUE THREAD

**Issue by rbeezer** [BooksHTML/mathbook-assets#55]
I think I have a good handle on what I'd like us to use for "list types" in HTML.

Can we have classes as follows?  Actual class names can be whatever makes sense.  These new classes should have CSS that sets "list-style-type:" to one of the values below.  

Maybe later we will want to adjust spacing above/below for all of these, when they occur as top-level/outermost lists, or maybe that is happening already.

On "ol" elements:
	decimal
	lower-alpha
	upper-alpha
	lower-roman
	upper-roman
	none

On "ul" elements:
	disc
	circle
	square
	none

**Comment by davidfarmer** [comment]
Lists seem to look fine now.
