### ISSUE TITLE
CSS class for hunks of pre-formatted text

### ISSUE THREAD

**Issue by rbeezer** [BooksHTML/mathbook-assets#59]
A new `<pre>` element in MBX just puts chunks of pre-formatted code into an HTML `<pre>` element.  Which is fine for now.  But conceivably we, or somebody else, will want to style it (indent, shadow-box, color background, etc).   For inline code we have 

```<tt class="code-inline">blah-blah</tt>```

which gets the nice grey background inline.  Can we decide on an analogue for the chunks?  Just need a name ("code-chunk"?) and I can write that out, too.   Any CSS work can come later.  I'm not going to be particular on this one.

Rob

**Comment by davidfarmer** [comment]
Presumably this has been addressed long ago.
