### ISSUE TITLE
Precise markup for the date of a document

### ISSUE THREAD

**Issue by rbeezer** [BooksHTML/mathbook-assets#60]
As part of the MBX "titlepage" element, you can supply a "date".  You can see it in action (ignore the "Draft" stuff):

http://abstract.ups.edu//beta/html/index.html

MBX writes out the content of the date into a "p" element with a centering text-align style.  Very bad, I know.  Somehow we let Michael escape without CSS for this.  Can we manufacture something?

The "address" element with class  .contributors  is used for the authors names, etc immediately prior, so that might provide the bulk of it, perhaps just with a smaller font (and maybe not in an address element?).

I have some recollection that Michael may have had a suggestion for this.  Perhaps it was this "time" element with a machine-readable "datetime" attribute:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time

I can see this being used other places, like the creation time of a version (which I place on very minor updates of FCLA when I do not increment the version number).

Rob

**Comment by rbeezer** [comment]
Stumbled upon it: Issue 17 in the MBX repo.

https://github.com/rbeezer/mathbook/issues/17

**Comment by davidfarmer** [comment]
Submit an new issue when this is implemented in MBX.
