### ISSUE TITLE
Disable clickability of Contents header of sidebar

### ISSUE THREAD

**Issue by rbeezer** [BooksHTML/mathbook-assets#61]
Once upon a time clicking this did something, but we backed out on that.  Now it appears clickable (cursor change on hover), but nothing happens (confusing users).

**Comment by rbeezer** [comment]
Maybe there just needs to be a minor change in the HTML output that looks like:
```<button class="sidebar-left-toggle-button button active">```
rather than editing the CSS itself.

**Comment by rbeezer** [comment]
Dropping the "active" in two places (my HTML converter) with a "sidebar-left-toggle-button" had no visual effect.  Nor replacing "active" by "inactive".

So I think this needs work here, as part of how the CSS behaves.

**Comment by davidfarmer** [comment]
It is inside something called a "button", so it acts like a button.

That makes sense, but it isn't what we want.

I'll (eventually) look into how to only change the CSS.  If the HTML has
to change, then that should wait until we also have to make other markup
changes.

**Comment by rbeezer** [comment]
Thanks, that does make sense.  No rush.

**Comment by davidfarmer** [comment]
Closing, because now the button hides the TOC.  That has its own separate issues.
