### ISSUE TITLE
Style information for an exercise group

### ISSUE THREAD

**Issue by rbeezer** [BooksHTML/mathbook-assets#62]
So it does not get lost.  "Exercise groups" are wrapped in

`<div class="exercisegroup">`

which needs styling via the CSS.  Latex just indents `2em`.  We experimented with FCLA using a dashed border, see Exercise RREF.C10.  No hurry at all, just laying down a marker.

https://groups.google.com/forum/#!topic/mathbook-xml-support/VOzyCjmaFiQ

**Comment by davidfarmer** [comment]
Previous and current work on exercises will address this.
