### ISSUE TITLE
CSS for attributions

### ISSUE THREAD

**Issue by rbeezer** [BooksHTML/mathbook-assets#64]
Block quotes, and material like a preface, have the names of authors follwing them (along with other information perhaps).  The HTNML cite tag does a good job, but in latex, I am making them land to the far right, but with left-justified text.  So some sample HTML to style:

```<cite class="attribution">Thomas W. Judson<br>Texas, 2015</cite>```

**Comment by davidfarmer** [comment]
That markup doesn't look right.  Resubmit if still an issue.
