### ISSUE TITLE
Two-up mode?

### ISSUE THREAD

**Issue by rbeezer** [BooksHTML/mathbook-assets#66]
Dima Pasechnik on sage-devel, suggests a 2-page display.  Probably only useful if left (and right) sidebars are collapsible.  Just recording this for future consideration.

https://groups.google.com/d/msg/sage-devel/KydSOsiYicg/r69sF7ALEQAJ

**Comment by davidfarmer** [comment]
If this is going to happen, it is so far into the future that it is just a distraction
to keep it on the issues list.
