### ISSUE TITLE
exercisegroup related CSS

### ISSUE THREAD

**Issue by rbeezer** [BooksHTML/mathbook-assets#77]
This is an intentional duplicate of

https://github.com/rbeezer/mathbook/issues/416

Please do the work here and mark that one completed?

**Comment by Alex-Jordan** [comment]
At http://spot.pcc.edu/math/orcca/section-cartesian-coordinates.html, exercises 6 and 7 are in an exercisegroup. The knowl for their solutions is not indented along with the exercise. (And I imagine the same would be true if there were an answer and a hint there.)

Relatively recent indentation of the exercisegroup exercises appears to have left behind these associated knowls.

**Comment by davidfarmer** [comment]
Those solution knowls look okay now.
